name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: üòâ Format
        run: deno task test:fmt
      - name: üòã Lint
        run: deno task test:lint
  # Type-Check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Git Checkout Module
  #       uses: actions/checkout@v2
  #     - name: Use Deno
  #       uses: denoland/setup-deno@v1
  #       with:
  #         deno-version: v1.x
  #     - name: üßê Type Check
  #       run: deno task check
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: üòé Test
        run: deno task test --coverage=coverage
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
  Build-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: üßê Build Check
        run: deno task build:check
